import React from 'react';
import { Link } from 'react-router-dom';
import { cn } from '@/lib/utils';

type LogoSize = 'sm' | 'md' | 'lg' | 'xl';

/** Rendered height per size. The mark is ~1.36:1, so width follows from this. */
const HEIGHTS: Record<LogoSize, string> = {
  sm: 'h-8',
  md: 'h-10',
  lg: 'h-14',
  xl: 'h-20',
};

interface LogoProps {
  size?: LogoSize;
  /** Wraps the mark in a link to the homepage. */
  to?: string | null;
  /** Adds the "Buy & Sell Marketplace" strapline beside the mark. */
  withStrapline?: boolean;
  /** Strapline colour, for dark vs light surfaces. */
  tone?: 'light' | 'dark';
  className?: string;
}

/**
 * The VMK Store logo.
 *
 * Single source for the mark so the header, footer and auth screens can never
 * drift apart. The artwork is a transparent PNG generated by
 * scripts/generate-brand-assets.mjs, served at two densities via srcset.
 *
 * The hover motion is CSS-only and sits behind `motion-safe:`, so it is absent
 * for anyone who has asked for reduced motion rather than merely shortened.
 */
const Logo = ({
  size = 'md',
  to = '/',
  withStrapline = false,
  tone = 'light',
  className,
}: LogoProps) => {
  const mark = (
    <span className={cn('group/logo inline-flex items-center gap-3', className)}>
      <img
        src="/brand/vmk-logo-160.png"
        srcSet="/brand/vmk-logo-160.png 1x, /brand/vmk-logo-320.png 2x"
        alt="VMK Online Store"
        // Intrinsic ratio of the trimmed artwork — reserves the right box
        // before the image loads, so the header does not jump.
        width={876}
        height={642}
        className={cn(
          'w-auto origin-left select-none object-contain drop-shadow-sm transition-transform duration-300 ease-out',
          'motion-safe:group-hover/logo:-translate-y-0.5 motion-safe:group-hover/logo:scale-[1.04]',
          HEIGHTS[size]
        )}
      />

      {withStrapline && (
        <span className="hidden sm:block">
          <span
            className={cn(
              'block text-2xs font-bold uppercase tracking-[0.2em]',
              tone === 'light' ? 'text-white/55' : 'text-muted-foreground'
            )}
          >
            Buy &amp; Sell Marketplace
          </span>
        </span>
      )}
    </span>
  );

  if (!to) return mark;

  return (
    <Link to={to} aria-label="VMK Online Store — home" className="inline-flex shrink-0">
      {mark}
    </Link>
  );
};

export default Logo;
