import { createHash } from 'crypto';
import { writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { electronicsProducts } from '../src/data/products';
import { fashionProducts } from '../src/data/fashionProducts';
import { groceryProducts } from '../src/data/groceryProducts';
import { homeProducts } from '../src/data/homeProducts';
import { beautyProducts } from '../src/data/beautyProducts';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

function deterministicUUID(input: string): string {
  const hash = createHash('md5').update(input).digest('hex');
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    '4' + hash.slice(13, 16),
    ((parseInt(hash[16], 16) & 0x3) | 0x8).toString(16) + hash.slice(17, 20),
    hash.slice(20, 32),
  ].join('-');
}

function esc(str: string | undefined): string {
  return str ? str.replace(/'/g, "''") : '';
}

const SYSTEM_SELLER_ID = '00000000-0000-4000-8000-000000000001';

const CATEGORY_IDS: Record<string, string> = {
  'Electronics':            deterministicUUID('cat-electronics'),
  'Fashion':                deterministicUUID('cat-fashion'),
  'Home & Kitchen':         deterministicUUID('cat-home-kitchen'),
  'Home & Garden':          deterministicUUID('cat-home-kitchen'),
  'Groceries':              deterministicUUID('cat-grocery'),
  'Beauty & Personal Care': deterministicUUID('cat-beauty'),
};

const allProducts = [
  ...electronicsProducts,
  ...fashionProducts,
  ...groceryProducts,
  ...homeProducts,
  ...beautyProducts,
] as { id: string; name: string; price: number; category: string; image?: string; description?: string }[];

const uuidMap: Record<string, string> = {};
for (const p of allProducts) {
  uuidMap[p.id] = deterministicUUID(`vmk-product-${p.id}`);
}

// ── SQL ──────────────────────────────────────────────────────────────────────
const lines: string[] = [];

lines.push(`-- VMK Store — Product Seed`);
lines.push(`-- Auto-generated by scripts/generate-seed.ts — do not edit manually.`);
lines.push(`-- Run AFTER schema.sql.\n`);

lines.push(`-- ── Step 1: Fix category IDs to deterministic UUIDs ────────────────────────`);
const uniqueCatNames = [...new Set(Object.keys(CATEGORY_IDS).filter(k => k !== 'Home & Garden'))];
for (const name of uniqueCatNames) {
  lines.push(`update public.categories set id = '${CATEGORY_IDS[name]}' where name = '${esc(name)}';`);
}
lines.push(`-- Map "Home & Garden" slug to same UUID as "Home & Kitchen" (same category)`);
lines.push(`update public.categories set id = '${CATEGORY_IDS['Home & Kitchen']}' where name = 'Home & Garden' and id != '${CATEGORY_IDS['Home & Kitchen']}';`);
lines.push('');

lines.push(`-- ── Step 2: System seller (VMK Store catalog account) ──────────────────────`);
lines.push(`-- This row lives in public.users only (no auth.users entry needed for seeding)`);
lines.push(`insert into public.users (id, email, first_name, last_name, account_type, is_verified)`);
lines.push(`values ('${SYSTEM_SELLER_ID}', 'catalog@vmkstore.com', 'VMK', 'Catalog', 'seller', true)`);
lines.push(`on conflict (id) do nothing;\n`);

lines.push(`-- ── Step 3: Products (${allProducts.length} total) ──────────────────────────────────────────`);
lines.push(`insert into public.products (id, seller_id, category_id, name, description, price, stock_quantity, status) values`);
const productRows = allProducts.map((p, i) => {
  const uuid = uuidMap[p.id];
  const catId = CATEGORY_IDS[p.category] ?? null;
  const catVal = catId ? `'${catId}'` : 'null';
  const desc = p.description ? `'${esc(p.description)}'` : 'null';
  const comma = i < allProducts.length - 1 ? ',' : '';
  return `  ('${uuid}', '${SYSTEM_SELLER_ID}', ${catVal}, '${esc(p.name)}', ${desc}, ${p.price}, 50, 'active')${comma}`;
});
lines.push(productRows.join('\n'));
lines.push(`on conflict (id) do nothing;\n`);

lines.push(`-- ── Step 4: Product images ─────────────────────────────────────────────────`);
const withImages = allProducts.filter(p => p.image);
lines.push(`insert into public.product_images (product_id, image_url, is_primary, display_order) values`);
const imageRows = withImages.map((p, i) => {
  const uuid = uuidMap[p.id];
  const comma = i < withImages.length - 1 ? ',' : '';
  return `  ('${uuid}', '${esc(p.image)}', true, 0)${comma}`;
});
lines.push(imageRows.join('\n'));
lines.push(`on conflict do nothing;\n`);

writeFileSync(path.join(root, 'scripts/seed-products.sql'), lines.join('\n'));
console.log(`✓ Written scripts/seed-products.sql  (${allProducts.length} products, ${withImages.length} images)`);

// ── UUID map for frontend ────────────────────────────────────────────────────
const mapEntries = Object.entries(uuidMap)
  .map(([k, v]) => `  '${k}': '${v}'`)
  .join(',\n');

const tsMap = `// Auto-generated by scripts/generate-seed.ts — do not edit manually.
export const PRODUCT_UUID_MAP: Record<string, string> = {
${mapEntries}
};

export function toProductUUID(staticId: string): string {
  return PRODUCT_UUID_MAP[staticId] ?? staticId;
}
`;

writeFileSync(path.join(root, 'src/lib/productIdMap.ts'), tsMap);
console.log(`✓ Written src/lib/productIdMap.ts`);
