/**
 * Generates scripts/seed-products.sql from the static product data files.
 * Run: node scripts/generate-seed.mjs
 *
 * Strategy: use a deterministic UUID per static product ID (v5 namespace)
 * so re-running always produces the same UUIDs. The same UUIDs are written
 * back into the TS data files so cart FK lookups work.
 */

import { createHash } from 'crypto';
import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..');

// Deterministic UUID v4-shaped from an input string (md5-based)
function deterministicUUID(input) {
  const hash = createHash('md5').update(input).digest('hex');
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    '4' + hash.slice(13, 16),   // version 4
    ((parseInt(hash[16], 16) & 0x3) | 0x8).toString(16) + hash.slice(17, 20), // variant
    hash.slice(20, 32),
  ].join('-');
}

// System seller UUID (fixed)
const SYSTEM_SELLER_ID = '00000000-0000-4000-8000-000000000001';

// Category slug → UUID (must match what schema.sql seeds)
// We derive these deterministically too so they match the categories table
// (schema.sql inserts with gen_random_uuid() — so we need to look them up at runtime
//  OR we fix the category IDs in schema.sql. We'll fix them here.)
const CATEGORY_IDS = {
  'Electronics':            deterministicUUID('cat-electronics'),
  'Fashion':                deterministicUUID('cat-fashion'),
  'Home & Kitchen':         deterministicUUID('cat-home-kitchen'),
  'Home & Garden':          deterministicUUID('cat-home-kitchen'),
  'Groceries':              deterministicUUID('cat-grocery'),
  'Beauty & Personal Care': deterministicUUID('cat-beauty'),
};

function esc(str) {
  return str ? str.replace(/'/g, "''") : '';
}

// ── Load all static product arrays ──────────────────────────────────────────

// We eval the TS files as plain JS by stripping type annotations
function loadTS(relPath) {
  const src = readFileSync(path.join(root, relPath), 'utf8')
    .replace(/export interface[\s\S]*?^}/mg, '')
    .replace(/: '[^']*'/g, '')
    .replace(/: string/g, '')
    .replace(/: number/g, '')
    .replace(/: boolean/g, '')
    .replace(/export const /g, 'const ')
    .replace(/export default /g, 'const _default = ');
  return src;
}

function evalProducts(src, varName) {
  const fn = new Function(`${src}; return ${varName};`);
  return fn();
}

const electronics = evalProducts(
  loadTS('src/data/products.ts'),
  'electronicsProducts'
);
const fashion = evalProducts(
  loadTS('src/data/fashionProducts.ts'),
  'fashionProducts'
);
const grocery = evalProducts(
  loadTS('src/data/groceryProducts.ts'),
  'groceryProducts'
);
const home = evalProducts(
  loadTS('src/data/homeProducts.ts'),
  'homeProducts'
);
const beauty = evalProducts(
  loadTS('src/data/beautyProducts.ts'),
  'beautyProducts'
);

const allProducts = [
  ...electronics,
  ...fashion,
  ...grocery,
  ...home,
  ...beauty,
];

// ── Build UUID map: staticId → UUID ─────────────────────────────────────────
const uuidMap = {};
for (const p of allProducts) {
  uuidMap[p.id] = deterministicUUID(`vmk-product-${p.id}`);
}

// ── Generate seed SQL ────────────────────────────────────────────────────────
const lines = [];

lines.push(`-- VMK Store — Product Seed`);
lines.push(`-- Auto-generated by scripts/generate-seed.mjs — do not edit manually.`);
lines.push(`-- Run AFTER schema.sql.\n`);

// Fix category IDs to be deterministic (override the gen_random_uuid() defaults)
lines.push(`-- ── Fix category IDs to deterministic values ──────────────────────────────`);
for (const [name, uuid] of Object.entries(CATEGORY_IDS)) {
  const dedupe = new Set(Object.values(CATEGORY_IDS));
  if (!dedupe.has(uuid)) continue;
  lines.push(`update public.categories set id = '${uuid}' where name = '${esc(name)}';`);
}
// Deduplicate (Home & Garden and Home & Kitchen share same ID)
const uniqueCats = {};
for (const [name, uuid] of Object.entries(CATEGORY_IDS)) {
  uniqueCats[uuid] = name;
}
lines.length = 0; // reset
lines.push(`-- VMK Store — Product Seed`);
lines.push(`-- Auto-generated by scripts/generate-seed.mjs — do not edit manually.`);
lines.push(`-- Run AFTER schema.sql.\n`);

lines.push(`-- ── Step 1: Fix category IDs to known deterministic UUIDs ─────────────────`);
const categoryUpdates = {
  'Electronics':            deterministicUUID('cat-electronics'),
  'Fashion':                deterministicUUID('cat-fashion'),
  'Home & Kitchen':         deterministicUUID('cat-home-kitchen'),
  'Groceries':              deterministicUUID('cat-grocery'),
  'Beauty & Personal Care': deterministicUUID('cat-beauty'),
};
for (const [name, uuid] of Object.entries(categoryUpdates)) {
  lines.push(`update public.categories set id = '${uuid}' where name = '${esc(name)}';`);
}
// Also update the FK references after changing category IDs (cascade handles this)
lines.push('');

// System seller in auth.users (using Supabase's admin — we insert directly for seeding)
lines.push(`-- ── Step 2: System seller account ─────────────────────────────────────────`);
lines.push(`insert into public.users (id, email, first_name, last_name, account_type, is_verified)`);
lines.push(`values ('${SYSTEM_SELLER_ID}', 'system@vmkstore.com', 'VMK', 'Store', 'seller', true)`);
lines.push(`on conflict (id) do nothing;\n`);

// Products
lines.push(`-- ── Step 3: Products ───────────────────────────────────────────────────────`);
lines.push(`insert into public.products (id, seller_id, category_id, name, price, stock_quantity, status) values`);

const productRows = allProducts.map((p, i) => {
  const uuid = uuidMap[p.id];
  const catId = CATEGORY_IDS[p.category] ?? null;
  const catVal = catId ? `'${catId}'` : 'null';
  const comma = i < allProducts.length - 1 ? ',' : '';
  return `  ('${uuid}', '${SYSTEM_SELLER_ID}', ${catVal}, '${esc(p.name)}', ${p.price}, 50, 'active')${comma}`;
});
lines.push(productRows.join('\n'));
lines.push(`on conflict (id) do nothing;\n`);

// Product images
lines.push(`-- ── Step 4: Product images ─────────────────────────────────────────────────`);
lines.push(`insert into public.product_images (product_id, image_url, is_primary, display_order) values`);

const imageRows = allProducts
  .filter(p => p.image)
  .map((p, i, arr) => {
    const uuid = uuidMap[p.id];
    const comma = i < arr.length - 1 ? ',' : '';
    return `  ('${uuid}', '${esc(p.image)}', true, 0)${comma}`;
  });
lines.push(imageRows.join('\n'));
lines.push(`on conflict do nothing;\n`);

const sql = lines.join('\n');
writeFileSync(path.join(root, 'scripts/seed-products.sql'), sql);
console.log(`✓ Written scripts/seed-products.sql (${allProducts.length} products)`);

// ── Write UUID map back to a TS file for the frontend ───────────────────────
const mapEntries = Object.entries(uuidMap)
  .map(([k, v]) => `  '${k}': '${v}'`)
  .join(',\n');

const tsMap = `// Auto-generated by scripts/generate-seed.mjs — do not edit manually.
// Maps static product IDs (e-001, f-001 …) to their Supabase UUIDs.
export const PRODUCT_UUID_MAP: Record<string, string> = {
${mapEntries}
};

export function toProductUUID(staticId: string): string {
  return PRODUCT_UUID_MAP[staticId] ?? staticId;
}
`;

writeFileSync(path.join(root, 'src/lib/productIdMap.ts'), tsMap);
console.log(`✓ Written src/lib/productIdMap.ts`);
